# Generated by Django 3.2.4 on 2021-09-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeOptionCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_option_combo_uid', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Attribute Option Combo',
                'db_table': 'attribute_option_combo',
            },
        ),
        migrations.CreateModel(
            name='CategoryOptionCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_option_combo_name', models.CharField(max_length=255)),
                ('category_option_combo_uid', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Category Option Combo',
                'db_table': 'category_option_combo',
            },
        ),
        migrations.CreateModel(
            name='OrganisationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_unit_name', models.CharField(max_length=255)),
                ('organisation_uid', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MasterData.facility')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterData.ward')),
            ],
            options={
                'db_table': 'organisation_units',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255)),
                ('dataset_uid', models.CharField(max_length=255)),
                ('attribute_option_combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DHIS.attributeoptioncombo')),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_element_name', models.CharField(max_length=255)),
                ('data_element_uid', models.CharField(max_length=255)),
                ('data_element_option', models.CharField(choices=[], max_length=255, unique=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DHIS.dataset')),
            ],
            options={
                'db_table': 'data_elements',
            },
        ),
        migrations.CreateModel(
            name='CategoryOptionComboDataElementMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_option_combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DHIS.categoryoptioncombo')),
                ('data_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DHIS.dataelement')),
            ],
            options={
                'verbose_name_plural': 'Category Option Combo Data Element Mapping',
                'db_table': 'category_option_combo_data_element_mapping',
            },
        ),
    ]
