# Generated by Django 3.2.4 on 2021-10-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHIS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='attribute_option_combo',
        ),
        migrations.RemoveField(
            model_name='dataelement',
            name='data_element_option',
        ),
        migrations.RemoveField(
            model_name='dataelement',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='organisationunit',
            name='ward',
        ),
        migrations.DeleteModel(
            name='AttributeOptionCombo',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
    ]
