# Generated by Django 3.2.4 on 2021-11-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHIS', '0002_auto_20211013_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelement',
            name='date_element_sys_name',
            field=models.CharField(choices=[('nhif_claims', 'NHIF Claims'), ('death_withing_the_facility', 'Death in the facility')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
