# Generated by Django 3.2.4 on 2021-11-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHIS', '0003_dataelement_date_element_sys_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoptioncombo',
            name='category_option_combo_sys_name',
            field=models.CharField(choices=[('claimed_amount', 'Claimed Amount'), ('computed_amount', 'Computed Amount'), ('accepted_amount', 'Accepted Amount'), ('loan_deductions', 'Loan Deductions'), ('other_deductions', 'Other Deductions'), ('paid_amount', 'Paid Amount')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='date_element_sys_name',
            field=models.CharField(choices=[('nhif_claims', 'NHIF Claims'), ('death_in_the_facility', 'Death in the facility')], max_length=30),
        ),
    ]
