# Generated by Django 3.2.4 on 2021-11-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHIS', '0005_auto_20211103_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataelement',
            old_name='date_element_sys_name',
            new_name='data_element_sys_name',
        ),
    ]
