# Generated by Django 3.2.4 on 2021-11-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHIS', '0006_rename_date_element_sys_name_dataelement_data_element_sys_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelement',
            name='payload_type',
            field=models.CharField(choices=[('nhif_claims', 'NHIF Claims'), ('death_within_facility', 'Death Within Facility')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='data_element_sys_name',
            field=models.CharField(choices=[('claimed_amount', 'Claimed Amount'), ('computed_amount', 'Computed Amount'), ('accepted_amount', 'Accepted Amount'), ('loan_deductions', 'Loan Deductions'), ('other_deductions', 'Other Deductions'), ('paid_amount', 'Paid Amount'), ('date_death_occurred', 'Date Death Occurred'), ('client_name', 'Client Name'), ('gender', 'Gender'), ('date_of_birth', 'Date of Birth'), ('place_of_death', 'Place of Death'), ('immediate_cause_of_death', 'Immediate Cause of Death'), ('underlying_cause_of_death', 'Underlying_Cause of Death')], max_length=30),
        ),
    ]
