# Generated by Django 3.2.4 on 2021-11-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHIS', '0007_auto_20211119_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelement',
            name='data_element_sys_name',
            field=models.CharField(choices=[('claimed_amount', 'Claimed Amount'), ('computed_amount', 'Computed Amount'), ('accepted_amount', 'Accepted Amount'), ('loan_deductions', 'Loan Deductions'), ('other_deductions', 'Other Deductions'), ('paid_amount', 'Paid Amount'), ('reporting_date', 'Reporting Date'), ('date_death_occurred', 'Date Death Occurred'), ('client_name', 'Client Name'), ('gender', 'Gender'), ('date_of_birth', 'Date of Birth'), ('place_of_death', 'Place of Death'), ('immediate_cause_of_death', 'Immediate Cause of Death'), ('underlying_cause_of_death', 'Underlying Cause of Death')], max_length=30),
        ),
    ]
