# Generated by Django 3.2 on 2023-07-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHIS', '0010_auto_20220730_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryoptioncombo',
            options={'verbose_name_plural': '3. Category Option Combo'},
        ),
        migrations.AlterModelOptions(
            name='categoryoptioncombodataelementmapping',
            options={'verbose_name_plural': '4. Category Option Combo Data Element Mapping'},
        ),
        migrations.AlterModelOptions(
            name='dataelement',
            options={'verbose_name_plural': '2. Data Elements'},
        ),
        migrations.AlterModelOptions(
            name='organisationunit',
            options={'verbose_name_plural': '1. Organization Units'},
        ),
    ]
