# Generated by Django 3.2 on 2023-07-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHIS', '0011_auto_20230725_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryoptioncombo',
            options={'verbose_name_plural': 'Category Option Combo'},
        ),
        migrations.AlterModelOptions(
            name='categoryoptioncombodataelementmapping',
            options={'verbose_name_plural': 'Category Option Combo Data Element Mapping'},
        ),
        migrations.AlterModelOptions(
            name='dataelement',
            options={'verbose_name_plural': 'Data Elements'},
        ),
        migrations.AlterModelOptions(
            name='organisationunit',
            options={'verbose_name_plural': 'Organization Units'},
        ),
    ]
