# Generated by Django 3.2.4 on 2021-09-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderRankingMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_service_provider_ranking_id', models.CharField(max_length=255)),
                ('local_service_provider_ranking_description', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
                ('service_provider_ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MasterData.serviceproviderranking')),
            ],
            options={
                'db_table': 'ServiceProviderRankingMappings',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfDeathMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_place_of_death_id', models.CharField(max_length=255)),
                ('local_place_of_death_description', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
                ('place_of_death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MasterData.placeofdeath')),
            ],
            options={
                'db_table': 'PlaceOfDeathMappings',
            },
        ),
        migrations.CreateModel(
            name='PayerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_payer_id', models.CharField(max_length=255)),
                ('local_payer_description', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MasterData.payer')),
            ],
            options={
                'db_table': 'PayerMappings',
            },
        ),
        migrations.CreateModel(
            name='GenderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_gender_description', models.CharField(max_length=50)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MasterData.gender')),
            ],
            options={
                'db_table': 'GenderMappings',
            },
        ),
        migrations.CreateModel(
            name='ExemptionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_exemption_id', models.CharField(max_length=255)),
                ('local_exemption_description', models.CharField(max_length=255)),
                ('exemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MasterData.exemption')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
            ],
            options={
                'db_table': 'ExemptionMappings',
            },
        ),
        migrations.CreateModel(
            name='DepartmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_department_id', models.CharField(max_length=255)),
                ('local_department_description', models.CharField(max_length=255)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MasterData.department')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
            ],
            options={
                'db_table': 'DepartmentMappings',
            },
        ),
    ]
