# Generated by Django 3.2.4 on 2021-12-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0005_rename_is_cpt_mapped_facility_uses_cpt_internally'),
        ('MappingsManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmapping',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='MasterData.facility'),
        ),
        migrations.AlterField(
            model_name='gendermapping',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='MasterData.facility'),
        ),
        migrations.AlterField(
            model_name='payermapping',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='MasterData.facility'),
        ),
        migrations.AlterField(
            model_name='placeofdeathmapping',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='MasterData.facility'),
        ),
        migrations.AlterField(
            model_name='serviceproviderrankingmapping',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='MasterData.facility'),
        ),
    ]
