# Generated by Django 3.2 on 2023-07-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MappingsManagement', '0005_auto_20220730_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentmapping',
            options={'verbose_name_plural': '4. Department Mappings'},
        ),
        migrations.AlterModelOptions(
            name='exemptionmapping',
            options={'verbose_name_plural': '4. Exemption Mappings'},
        ),
        migrations.AlterModelOptions(
            name='gendermapping',
            options={'verbose_name_plural': '3. Gender Mappings'},
        ),
        migrations.AlterModelOptions(
            name='payermapping',
            options={'verbose_name_plural': '4. Payer Mappings'},
        ),
        migrations.AlterModelOptions(
            name='placeofdeathmapping',
            options={'verbose_name_plural': '1. Place of Death Mappings'},
        ),
        migrations.AlterModelOptions(
            name='serviceproviderrankingmapping',
            options={'verbose_name_plural': '2. Service Provider Rankings Mappings'},
        ),
    ]
