# Generated by Django 3.2 on 2023-07-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MappingsManagement', '0006_auto_20230725_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentmapping',
            options={'verbose_name_plural': 'Department Mappings'},
        ),
        migrations.AlterModelOptions(
            name='exemptionmapping',
            options={'verbose_name_plural': 'Exemption Mappings'},
        ),
        migrations.AlterModelOptions(
            name='gendermapping',
            options={'verbose_name_plural': 'Gender Mappings'},
        ),
        migrations.AlterModelOptions(
            name='payermapping',
            options={'verbose_name_plural': 'Payer Mappings'},
        ),
        migrations.AlterModelOptions(
            name='placeofdeathmapping',
            options={'verbose_name_plural': 'Place of Death Mappings'},
        ),
        migrations.AlterModelOptions(
            name='serviceproviderrankingmapping',
            options={'verbose_name_plural': 'Service Provider Rankings Mappings'},
        ),
    ]
