# Generated by Django 3.2.4 on 2021-09-28 08:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedOccupancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Bed occupancy',
                'db_table': 'BedOccupancy',
            },
        ),
        migrations.CreateModel(
            name='BedOccupancyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('ward_id', models.CharField(max_length=100)),
                ('ward_name', models.CharField(max_length=255)),
                ('admission_date', models.DateField(default=datetime.date.today)),
                ('date', models.DateField()),
                ('bed_occupancy', models.DecimalField(decimal_places=4, max_digits=7)),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'BedOccupancyReport',
            },
        ),
        migrations.CreateModel(
            name='DeathByDiseaseCaseAtFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Death by Disease Cases at Facility',
                'db_table': 'DeathByDiseaseCaseAtFacility',
            },
        ),
        migrations.CreateModel(
            name='DeathByDiseaseCaseNotAtFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Death by Disease Cases Not at Facility',
                'db_table': 'DeathByDiseaseCaseNotAtFacility',
            },
        ),
        migrations.CreateModel(
            name='RevenueReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Revenue received',
                'db_table': 'RevenueReceived',
            },
        ),
        migrations.CreateModel(
            name='ServiceReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Services Received',
                'db_table': 'ServiceReceived',
            },
        ),
        migrations.CreateModel(
            name='ServiceReceivedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('department_id', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('med_svc_code', models.CharField(max_length=255)),
                ('icd_10_code', models.CharField(blank=True, max_length=255, null=True)),
                ('service_date', models.DateField()),
                ('service_provider_ranking_id', models.CharField(max_length=255)),
                ('visit_type', models.CharField(max_length=255)),
                ('service_received', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.servicereceived')),
            ],
            options={
                'verbose_name_plural': 'Services Received Items',
                'db_table': 'ServiceReceivedItems',
            },
        ),
        migrations.CreateModel(
            name='RevenueReceivedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_trans_id', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('patient_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('med_svc_code', models.CharField(max_length=50)),
                ('payer_id', models.CharField(max_length=50)),
                ('exemption_category_id', models.CharField(blank=True, max_length=100, null=True)),
                ('billed_amount', models.IntegerField(default=0)),
                ('waived_amount', models.IntegerField(default=0)),
                ('service_provider_ranking_id', models.CharField(max_length=255)),
                ('revenue_received', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.revenuereceived')),
            ],
            options={
                'verbose_name_plural': 'Revenue Received Items',
                'db_table': 'RevenueReceivedItems',
            },
        ),
        migrations.CreateModel(
            name='DeathByDiseaseCaseNotAtFacilityItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_death_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('icd_10_code', models.CharField(blank=True, max_length=255, null=True)),
                ('date_death_occurred', models.DateField()),
                ('death_id', models.CharField(max_length=100)),
                ('death_by_disease_case_not_at_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.deathbydiseasecasenotatfacility')),
            ],
            options={
                'verbose_name_plural': 'Death by Disease Cases Not at Facility Items',
                'db_table': 'DeathByDiseaseCaseNotAtFacilityItems',
            },
        ),
        migrations.CreateModel(
            name='DeathByDiseaseCaseAtFacilityItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=255)),
                ('ward_id', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('icd_10_code', models.CharField(blank=True, max_length=255, null=True)),
                ('date_death_occurred', models.DateField()),
                ('death_by_disease_case_at_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.deathbydiseasecaseatfacility')),
            ],
            options={
                'verbose_name_plural': 'Death by Disease Cases at Facility Items',
                'db_table': 'DeathByDiseaseCaseAtFacilityItems',
            },
        ),
        migrations.CreateModel(
            name='BedOccupancyItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('ward_name', models.CharField(max_length=255)),
                ('ward_id', models.CharField(max_length=255)),
                ('bed_occupancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.bedoccupancy')),
            ],
            options={
                'verbose_name_plural': 'Bed occupancyItems',
                'db_table': 'BedOccupancyItems',
            },
        ),
    ]
