# Generated by Django 3.2.4 on 2021-10-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20211015_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedoccupancyitems',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
