# Generated by Django 3.2.4 on 2021-10-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_bedoccupancyitems_discharge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedoccupancy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deathbydiseasecaseatfacility',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deathbydiseasecasenotatfacility',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='revenuereceived',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicereceived',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
