# Generated by Django 3.2.4 on 2021-06-21 05:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20210415_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedOccupancyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('ward_id', models.CharField(max_length=100)),
                ('ward_name', models.CharField(max_length=255)),
                ('admission_date', models.DateField(default=datetime.date.today)),
                ('date', models.DateField()),
                ('bed_occupancy', models.DecimalField(decimal_places=4, max_digits=7)),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'BedOccupancyReport',
            },
        ),
        migrations.CreateModel(
            name='PayloadThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_description', models.CharField(max_length=255)),
                ('payload_code', models.CharField(max_length=255)),
                ('percentage_threshold', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'PayloadThreshold',
            },
        ),
        migrations.CreateModel(
            name='PayloadUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_uploaded', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('SVCREC', 'SVCREC'), ('DDC', 'DDC'), ('DDCOUT', 'DDCOUT'), ('REV', 'REV'), ('BEDOCC', 'BEDOCC')], max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads')),
            ],
            options={
                'db_table': 'PayloadUploads',
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('rule_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ValidationRules',
            },
        ),
        migrations.RemoveField(
            model_name='transactionsummary',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='transactionsummary',
            name='failed_records',
        ),
        migrations.RemoveField(
            model_name='transactionsummary',
            name='passed_records',
        ),
        migrations.RemoveField(
            model_name='transactionsummary',
            name='payload',
        ),
        migrations.AddField(
            model_name='transactionsummary',
            name='message_type',
            field=models.CharField(choices=[('SVCREC', 'SVCREC'), ('DDC', 'DDC'), ('DDCOUT', 'DDCOUT'), ('REV', 'REV'), ('BEDOCC', 'BEDOCC')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionsummary',
            name='org_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionsummary',
            name='total_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionsummary',
            name='total_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bedoccupancyitems',
            name='ward_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deathbydiseasecaseatfacilityitems',
            name='icd_10_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deathbydiseasecasenotatfacilityitems',
            name='death_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deathbydiseasecasenotatfacilityitems',
            name='icd_10_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deathbydiseasecasenotatfacilityitems',
            name='place_of_death_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='revenuereceiveditems',
            name='billed_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuereceiveditems',
            name='waived_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TransactionSummaryLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_object', models.TextField()),
                ('transaction_status', models.BooleanField(default=0)),
                ('error_message', models.TextField()),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.transactionsummary')),
            ],
            options={
                'verbose_name_plural': 'Transactions summary lines',
                'db_table': 'TransactionSummaryLine',
            },
        ),
        migrations.CreateModel(
            name='FieldValidationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('SVCREC', 'SVCREC'), ('DDC', 'DDC'), ('DDCOUT', 'DDCOUT'), ('REV', 'REV'), ('BEDOCC', 'BEDOCC')], max_length=100)),
                ('field', models.CharField(max_length=255)),
                ('validation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.validationrule')),
            ],
            options={
                'db_table': 'FieldValidationMappings',
            },
        ),
    ]
