# Generated by Django 3.2.4 on 2021-10-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20211026_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedoccupancy',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deathbydiseasecaseatfacility',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deathbydiseasecasenotatfacility',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='revenuereceived',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='servicereceived',
            name='is_active',
        ),
    ]
