# Generated by Django 3.2.4 on 2021-10-26 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationManagement', '0002_transactionsummary_is_active'),
        ('Core', '0005_auto_20211026_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedoccupancy',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ValidationManagement.transactionsummary'),
        ),
        migrations.AddField(
            model_name='deathbydiseasecaseatfacility',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ValidationManagement.transactionsummary'),
        ),
        migrations.AddField(
            model_name='deathbydiseasecasenotatfacility',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ValidationManagement.transactionsummary'),
        ),
        migrations.AddField(
            model_name='revenuereceived',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ValidationManagement.transactionsummary'),
        ),
        migrations.AddField(
            model_name='servicereceived',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ValidationManagement.transactionsummary'),
        ),
    ]
