# Generated by Django 3.2.4 on 2021-11-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20211026_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deathbydiseasecaseatfacilityitems',
            old_name='icd_10_code',
            new_name='intermediate_condition',
        ),
        migrations.RenameField(
            model_name='deathbydiseasecasenotatfacilityitems',
            old_name='icd_10_code',
            new_name='intermediate_condition',
        ),
        migrations.RemoveField(
            model_name='servicereceiveditems',
            name='icd_10_code',
        ),
        migrations.AddField(
            model_name='deathbydiseasecaseatfacilityitems',
            name='cause_of_death',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deathbydiseasecaseatfacilityitems',
            name='underlying_condition',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deathbydiseasecasenotatfacilityitems',
            name='cause_of_death',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deathbydiseasecasenotatfacilityitems',
            name='underlying_condition',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicereceiveditems',
            name='confirmed_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicereceiveditems',
            name='differential_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicereceiveditems',
            name='provisional_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deathbydiseasecaseatfacilityitems',
            name='date_death_occurred',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='revenuereceiveditems',
            name='med_svc_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicereceiveditems',
            name='med_svc_code',
            field=models.TextField(),
        ),
    ]
