# Generated by Django 3.2.4 on 2021-11-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_auto_20211102_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deathbydiseasecaseatfacilityitems',
            old_name='intermediate_condition',
            new_name='immediate_cause_of_death',
        ),
        migrations.RenameField(
            model_name='deathbydiseasecaseatfacilityitems',
            old_name='underlying_condition',
            new_name='underlying_cause_of_death',
        ),
        migrations.RenameField(
            model_name='deathbydiseasecasenotatfacilityitems',
            old_name='intermediate_condition',
            new_name='immediate_cause_of_death',
        ),
        migrations.RemoveField(
            model_name='deathbydiseasecasenotatfacilityitems',
            name='underlying_condition',
        ),
        migrations.AddField(
            model_name='deathbydiseasecasenotatfacilityitems',
            name='underlying_cause_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
