# Generated by Django 3.2.4 on 2021-11-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_auto_20211102_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedoccupancyitems',
            options={'verbose_name_plural': 'Bed occupancy Items'},
        ),
    ]
