# Generated by Django 3.2.4 on 2021-11-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_bedoccupancyitems_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathbydiseasecaseatfacilityitems',
            name='date_death_occurred',
            field=models.DateField(),
        ),
    ]
