# Generated by Django 3.2.4 on 2021-11-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_deathbydiseasecaseatfacilityitems_date_death_occurred'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedoccupancy',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
