# Generated by Django 3.2.4 on 2021-11-21 19:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_bedoccupancy_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuereceiveditems',
            name='med_svc_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='servicereceiveditems',
            name='confirmed_diagnosis',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicereceiveditems',
            name='differential_diagnosis',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicereceiveditems',
            name='med_svc_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='servicereceiveditems',
            name='provisional_diagnosis',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=[], size=None),
            preserve_default=False,
        ),
    ]
