# Generated by Django 3.2.4 on 2021-12-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_auto_20211121_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuereceiveditems',
            name='billed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='revenuereceiveditems',
            name='waived_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
