# Generated by Django 3.2 on 2022-07-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_auto_20211214_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesReceivedDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('department_id', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(max_length=255)),
                ('med_svc_code', models.TextField()),
                ('service_date', models.DateField(max_length=255)),
                ('service_provider_ranking_id', models.CharField(max_length=255)),
                ('visit_type', models.CharField(max_length=255)),
                ('service_received_id', models.IntegerField(max_length=255)),
                ('confirmed_diagnosis', models.TextField()),
                ('differential_diagnosis', models.TextField()),
                ('provisional_diagnosis', models.TextField()),
                ('hdr_gender', models.CharField(max_length=255)),
                ('org_name', models.CharField(max_length=255)),
                ('cpt_code', models.CharField(max_length=255)),
                ('cpt_description', models.CharField(max_length=255)),
                ('cpt_category', models.CharField(max_length=255)),
                ('hdr_service_provider_rankings', models.CharField(max_length=255)),
                ('icd10_code', models.CharField(max_length=255)),
                ('icd10_code_description', models.CharField(max_length=255)),
                ('icd10_sub_category', models.CharField(max_length=255)),
                ('icd10_categories', models.CharField(max_length=255)),
                ('icd10_chapter', models.CharField(max_length=255)),
                ('district_council', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ServicesReceivedDataset',
            },
        ),
    ]
