# Generated by Django 3.2 on 2022-07-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_servicesreceiveddataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='confirmed_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='cpt_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='cpt_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='cpt_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='department_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='differential_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='district_council',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='hdr_gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='hdr_service_provider_rankings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='icd10_categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='icd10_chapter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='icd10_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='icd10_code_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='icd10_sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='med_svc_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='provisional_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='service_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='service_provider_ranking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='service_received_id',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesreceiveddataset',
            name='visit_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
