# Generated by Django 3.2 on 2023-07-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_auto_20220731_0320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedoccupancy',
            options={'verbose_name_plural': '7. Bed occupancy'},
        ),
        migrations.AlterModelOptions(
            name='bedoccupancyitems',
            options={'verbose_name_plural': '8. Bed occupancy Items'},
        ),
        migrations.AlterModelOptions(
            name='bedoccupancyreport',
            options={'verbose_name_plural': '9. Bed occupancy Report'},
        ),
        migrations.AlterModelOptions(
            name='deathbydiseasecaseatfacility',
            options={'verbose_name_plural': '3. Death by Disease Cases at Facility'},
        ),
        migrations.AlterModelOptions(
            name='deathbydiseasecaseatfacilityitems',
            options={'verbose_name_plural': '4. Death by Disease Cases at Facility Items'},
        ),
        migrations.AlterModelOptions(
            name='deathbydiseasecasenotatfacility',
            options={'verbose_name_plural': '5. Death by Disease Cases Not at Facility'},
        ),
        migrations.AlterModelOptions(
            name='deathbydiseasecasenotatfacilityitems',
            options={'verbose_name_plural': '6. Death by Disease Cases Not at Facility Items'},
        ),
        migrations.AlterModelOptions(
            name='revenuereceived',
            options={'verbose_name_plural': '10. Revenue received'},
        ),
        migrations.AlterModelOptions(
            name='revenuereceiveditems',
            options={'verbose_name_plural': '11. Revenue Received Items'},
        ),
        migrations.AlterModelOptions(
            name='servicereceived',
            options={'verbose_name_plural': '1. Services Received'},
        ),
        migrations.AlterModelOptions(
            name='servicereceiveditems',
            options={'verbose_name_plural': '2. Services Received Items'},
        ),
        migrations.AlterModelOptions(
            name='servicesreceiveddataset',
            options={'verbose_name_plural': '12. Services Received Dataset'},
        ),
    ]
