# Generated by Django 3.2 on 2023-07-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_auto_20230725_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedoccupancy',
            options={'verbose_name_plural': 'Bed occupancy'},
        ),
        migrations.AlterModelOptions(
            name='bedoccupancyitems',
            options={'verbose_name_plural': 'Bed occupancy Items'},
        ),
        migrations.AlterModelOptions(
            name='bedoccupancyreport',
            options={'verbose_name_plural': 'Bed occupancy Report'},
        ),
        migrations.AlterModelOptions(
            name='deathbydiseasecaseatfacility',
            options={'verbose_name_plural': 'Death by Disease Cases at Facility'},
        ),
        migrations.AlterModelOptions(
            name='deathbydiseasecaseatfacilityitems',
            options={'verbose_name_plural': 'Death by Disease Cases at Facility Items'},
        ),
        migrations.AlterModelOptions(
            name='deathbydiseasecasenotatfacility',
            options={'verbose_name_plural': 'Death by Disease Cases Not at Facility'},
        ),
        migrations.AlterModelOptions(
            name='deathbydiseasecasenotatfacilityitems',
            options={'verbose_name_plural': 'Death by Disease Cases Not at Facility Items'},
        ),
        migrations.AlterModelOptions(
            name='revenuereceived',
            options={'verbose_name_plural': 'Revenue received'},
        ),
        migrations.AlterModelOptions(
            name='revenuereceiveditems',
            options={'verbose_name_plural': 'Revenue Received Items'},
        ),
        migrations.AlterModelOptions(
            name='servicereceived',
            options={'verbose_name_plural': 'Services Received'},
        ),
        migrations.AlterModelOptions(
            name='servicereceiveditems',
            options={'verbose_name_plural': 'Services Received Items'},
        ),
        migrations.AlterModelOptions(
            name='servicesreceiveddataset',
            options={'verbose_name_plural': 'Services Received Dataset'},
        ),
    ]
