# Generated by Django 3.2.4 on 2021-06-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facility',
            table='facility',
        ),
    ]
