# Generated by Django 3.2.4 on 2021-11-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_cpt_mapped',
            field=models.BooleanField(default=1),
        ),
    ]
