# Generated by Django 3.2.4 on 2021-06-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0002_alter_facility_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facility',
            table='Facility',
        ),
    ]
