# Generated by Django 3.2.4 on 2021-11-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0003_facility_dhis_org_unit_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='dhis_org_unit_uid',
        ),
    ]
