# Generated by Django 3.2.4 on 2021-11-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0004_remove_facility_dhis_org_unit_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='is_cpt_mapped',
            new_name='uses_cpt_internally',
        ),
    ]
