# Generated by Django 3.2 on 2023-07-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0006_auto_20230725_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='districtcouncil',
            options={'verbose_name_plural': 'District Councils'},
        ),
        migrations.AlterModelOptions(
            name='exemption',
            options={'verbose_name_plural': 'Exemptions'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name_plural': 'Gender'},
        ),
        migrations.AlterModelOptions(
            name='payer',
            options={'verbose_name_plural': 'Payers'},
        ),
        migrations.AlterModelOptions(
            name='placeofdeath',
            options={'verbose_name_plural': 'Places Of Death'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='serviceproviderranking',
            options={'verbose_name_plural': 'Service Provider Rankings'},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'verbose_name_plural': 'Wards'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name_plural': 'Zones'},
        ),
    ]
