# Generated by Django 3.2.4 on 2021-09-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TerminologyServicesManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icd10code',
            old_name='icd_10_code_sub_category',
            new_name='icd10_code_sub_category',
        ),
        migrations.RenameField(
            model_name='icd10codesubcategory',
            old_name='icd_10_code_category',
            new_name='icd10_code_category',
        ),
    ]
