# Generated by Django 3.2.4 on 2021-09-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TerminologyServicesManagement', '0002_auto_20210929_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd10code',
            name='icd10_code_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_category', to='TerminologyServicesManagement.icd10codesubcategory'),
        ),
        migrations.AlterField(
            model_name='icd10codesubcategory',
            name='icd10_code_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='TerminologyServicesManagement.icd10codecategory'),
        ),
        migrations.AlterField(
            model_name='icd10subcode',
            name='icd10_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code', to='TerminologyServicesManagement.icd10code'),
        ),
    ]
