# Generated by Django 3.2.4 on 2021-10-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TerminologyServicesManagement', '0005_auto_20211008_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icd10subcode',
            old_name='description',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='icd10subcode',
            old_name='sub_code',
            new_name='sub_code1',
        ),
    ]
