# Generated by Django 3.2.4 on 2021-10-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TerminologyServicesManagement', '0006_auto_20211008_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icd10subcode',
            old_name='description1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='icd10subcode',
            old_name='sub_code1',
            new_name='sub_code',
        ),
    ]
