# Generated by Django 3.2.4 on 2021-11-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TerminologyServicesManagement', '0007_auto_20211008_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='icd10codecategory',
            name='identifier',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icd10codesubcategory',
            name='identifier',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
