# Generated by Django 3.2.4 on 2021-11-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TerminologyServicesManagement', '0008_auto_20211104_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cptcode',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
