# Generated by Django 3.2.4 on 2021-11-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TerminologyServicesManagement', '0009_alter_cptcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cptcode',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
