# Generated by Django 3.2.4 on 2021-11-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TerminologyServicesManagement', '0010_alter_cptcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cptcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='icd10subcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
