# Generated by Django 3.2.4 on 2021-10-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_hfr_code', models.CharField(max_length=255)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('period', models.CharField(max_length=255)),
                ('computed_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('accepted_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('loan_deductions', models.DecimalField(decimal_places=2, max_digits=9)),
                ('other_deductions', models.DecimalField(decimal_places=2, max_digits=9)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'Claims',
            },
        ),
    ]
