# Generated by Django 3.2.4 on 2021-12-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NHIF', '0003_claims_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='accepted_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='claims',
            name='claimed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='claims',
            name='computed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='claims',
            name='loan_deductions',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='claims',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='claims',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
