# Generated by Django 3.1.6 on 2021-12-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NHIF', '0004_auto_20211214_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
