# Generated by Django 3.2 on 2023-07-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NHIF', '0006_alter_claims_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claims',
            options={'verbose_name_plural': '1. Claims'},
        ),
    ]
