# Generated by Django 3.2 on 2023-07-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NHIF', '0007_alter_claims_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claims',
            options={'verbose_name_plural': 'Claims'},
        ),
    ]
