# Generated by Django 3.2.4 on 2021-10-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsummary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
