# Generated by Django 3.2.4 on 2021-11-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0004_remove_facility_dhis_org_unit_uid'),
        ('ValidationManagement', '0002_transactionsummary_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payloadupload',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='MasterData.facility'),
            preserve_default=False,
        ),
    ]
