# Generated by Django 3.2.4 on 2021-11-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationManagement', '0003_payloadupload_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayloadFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('SVCREC', 'SVCREC'), ('DDC', 'DDC'), ('DDCOUT', 'DDCOUT'), ('REV', 'REV'), ('BEDOCC', 'BEDOCC')], max_length=100)),
                ('field', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PayloadFieldMappings',
            },
        ),
    ]
