# Generated by Django 3.2.4 on 2021-11-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationManagement', '0004_payloadfieldmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payloadfieldmapping',
            name='message_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ValidationManagement.payloadthreshold'),
        ),
    ]
