# Generated by Django 3.2.4 on 2021-11-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationManagement', '0006_fieldvalidationmapping_new_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldvalidationmapping',
            name='new_message_type',
        ),
    ]
