# Generated by Django 3.1.6 on 2021-12-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationManagement', '0010_auto_20211217_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsummary',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
    ]
